<?php

declare(strict_types=1);

namespace App\Livewire;

use App\Models\Course;
use App\Services\CulqiService;
use App\Services\EnrollmentService;
use App\Services\PaymentService;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\Auth;
use Livewire\Attributes\Layout;
use Livewire\Component;

#[Layout('layouts.app')]
class CourseCheckout extends Component
{
    public Course $course;

    /**
     * Mount the component.
     */
    public function mount(
        Course $course,
        EnrollmentService $enrollmentService
    ): void {
        $this->course = $course;

        // Check if user is authenticated
        if (auth()->check()) {
            // Check if user already has access
            if ($enrollmentService->checkAccess(Auth::user(), $course)) {
                session()->flash('message', 'Ya tienes este curso.');
                $this->redirect(route('student.dashboard'));
            }
        }
        // If user is not authenticated (Guest), allow component to load normally
        // so they can pay and register
    }

    /**
     * Process the payment with Culqi.
     *
     * @param string $tokenId The token ID generated by Culqi
     * @param string $email The email from the token
     */
    public function processPayment(
        string $tokenId,
        string $email,
        CulqiService $culqiService,
        PaymentService $paymentService
    ): void {
        $user = Auth::user();

        // Validate that the email matches the authenticated user
        if ($user->email !== $email) {
            session()->flash('error', 'El email del pago no coincide con tu cuenta.');
            return;
        }

        // Create charge using CulqiService
        $result = $culqiService->createCharge(
            user: $user,
            course: $this->course,
            tokenId: $tokenId
        );

        if ($result['success']) {
            // Extract charge ID from the response
            // Handle both object and array responses
            $chargeData = $result['data'];
            $chargeId = null;

            if (is_object($chargeData)) {
                $chargeId = $chargeData->id ?? null;
            } elseif (is_array($chargeData)) {
                $chargeId = $chargeData['id'] ?? null;
            }

            if (!$chargeId) {
                session()->flash('error', 'No se pudo obtener el ID del cargo. Por favor, contacta con soporte.');
                return;
            }

            // Create order and enroll user
            $paymentService->createCulqiOrder(
                user: $user,
                course: $this->course,
                transactionId: $chargeId
            );

            // Redirect to course with success message
            session()->flash('message', 'Compra realizada exitosamente.');
            $this->redirect(route('course.learn', $this->course));
        } else {
            // Show error message
            $errorMessage = $result['message'] ?? 'Ocurrió un error al procesar el pago. Por favor, intenta nuevamente.';
            session()->flash('error', $errorMessage);
        }
    }

    /**
     * Render the component.
     */
    public function render(): View
    {
        return view('livewire.course-checkout');
    }
}

