<?php

declare(strict_types=1);

namespace App\Livewire;

use App\Models\Course;
use App\Models\User;
use App\Services\CulqiService;
use App\Services\EnrollmentService;
use App\Services\PaymentService;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Livewire\Attributes\Layout;
use Livewire\Component;

#[Layout('layouts.app')]
class CourseCheckout extends Component
{
    public Course $course;

    public string $name = '';

    public string $email = '';

    public string $password = '';

    /**
     * Mount the component.
     */
    public function mount(
        Course $course,
        EnrollmentService $enrollmentService
    ): void {
        $this->course = $course;

        // Check if user is authenticated
        if (auth()->check()) {
            // Check if user already has access
            if ($enrollmentService->checkAccess(Auth::user(), $course)) {
                session()->flash('message', 'Ya tienes este curso.');
                $this->redirect(route('student.dashboard'));
            }
        }
        // If user is not authenticated (Guest), allow component to load normally
        // so they can pay and register
    }

    /**
     * Validate form data and dispatch payment initialization event.
     */
    public function validateAndPay(): void
    {
        // If user is guest, validate registration fields
        if (!auth()->check()) {
            $this->validate([
                'name' => ['required', 'string', 'max:255'],
                'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email'],
                'password' => ['required', 'string', 'min:8'],
            ], [
                'name.required' => 'El nombre es obligatorio.',
                'email.required' => 'El correo electrónico es obligatorio.',
                'email.email' => 'El correo electrónico debe tener un formato válido.',
                'email.unique' => 'Este correo electrónico ya está registrado.',
                'password.required' => 'La contraseña es obligatoria.',
                'password.min' => 'La contraseña debe tener al menos 8 caracteres.',
            ]);
        }

        // Dispatch event to initialize Culqi payment
        $this->dispatch('init-payment');
    }

    /**
     * Process the payment with Culqi.
     *
     * @param string $tokenId The token ID generated by Culqi
     * @param string $email The email from the token
     */
    public function processPayment(
        string $tokenId,
        string $email,
        CulqiService $culqiService,
        PaymentService $paymentService
    ): void {
        $user = Auth::user();

        // If user is not authenticated (Guest), create the user account
        if (!$user) {
            // Validate that the email from token matches the form email
            if ($this->email !== $email) {
                session()->flash('error', 'El email del pago no coincide con el email registrado.');
                return;
            }

            // Create the user with the form data
            $user = User::create([
                'name' => $this->name,
                'email' => $this->email,
                'password' => Hash::make($this->password),
            ]);

            // Automatically log in the newly created user
            Auth::login($user);
        } else {
            // Validate that the email matches the authenticated user
            if ($user->email !== $email) {
                session()->flash('error', 'El email del pago no coincide con tu cuenta.');
                return;
            }
        }

        // Create charge using CulqiService
        $result = $culqiService->createCharge(
            user: $user,
            course: $this->course,
            tokenId: $tokenId
        );

        if ($result['success']) {
            // Extract charge ID from the response
            // Handle both object and array responses
            $chargeData = $result['data'];
            $chargeId = null;

            if (is_object($chargeData)) {
                $chargeId = $chargeData->id ?? null;
            } elseif (is_array($chargeData)) {
                $chargeId = $chargeData['id'] ?? null;
            }

            if (!$chargeId) {
                session()->flash('error', 'No se pudo obtener el ID del cargo. Por favor, contacta con soporte.');
                return;
            }

            // Create order and enroll user
            $paymentService->createCulqiOrder(
                user: $user,
                course: $this->course,
                transactionId: $chargeId
            );

            // Redirect to course with success message
            session()->flash('message', 'Compra realizada exitosamente.');
            $this->redirect(route('course.learn', $this->course));
        } else {
            // Show error message
            $errorMessage = $result['message'] ?? 'Ocurrió un error al procesar el pago. Por favor, intenta nuevamente.';
            session()->flash('error', $errorMessage);
        }
    }

    /**
     * Render the component.
     */
    public function render(): View
    {
        return view('livewire.course-checkout');
    }
}

